name: Check
on: 
  push:
    branches: [ dev ]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: ci install
      - name: Lint
        run: npm run lint